import { useCallback, useEffect, useRef } from "react";
import type { Dispatch, MutableRefObject } from "react";
import type { RateLimitSnapshot, TurnPlan } from "@/types";
import { interruptTurn as interruptTurnService } from "@services/tauri";
import { getThreadTimestamp } from "@utils/threadItems";
import {
  asString,
  normalizePlanUpdate,
  normalizeRateLimits,
  normalizeTokenUsage,
} from "@threads/utils/threadNormalize";
import { looksAutoGeneratedThreadName } from "@threads/utils/threadNaming";
import { getThreadDisplayTitle } from "@threads/utils/threadSummary";
import {
  getLiveThreadSubagentSummaryPatch,
  getThreadStartAction,
  normalizeThreadStatusType,
  resetThreadTurnState,
  shouldClearCompletedPlanForThread,
  shouldIgnoreOrphanSubagentThread,
} from "./threadTurnEventHelpers";
import type { ThreadAction } from "./useThreadsReducer";

type UseThreadTurnEventsOptions = {
  dispatch: Dispatch<ThreadAction>;
  planByThreadRef: MutableRefObject<Record<string, TurnPlan | null>>;
  getCurrentRateLimits?: (workspaceId: string) => RateLimitSnapshot | null;
  getCustomName: (workspaceId: string, threadId: string) => string | undefined;
  isThreadHidden: (workspaceId: string, threadId: string) => boolean;
  setThreadLoaded: (threadId: string, isLoaded: boolean) => void;
  markProcessing: (threadId: string, isProcessing: boolean) => void;
  markReviewing: (threadId: string, isReviewing: boolean) => void;
  setActiveTurnId: (threadId: string, turnId: string | null) => void;
  getActiveTurnId: (threadId: string) => string | null;
  pendingInterruptsRef: MutableRefObject<Set<string>>;
  pushThreadErrorMessage: (
    threadId: string,
    message: string,
    turnId?: string,
  ) => void;
  safeMessageActivity: () => void;
  recordThreadActivity: (workspaceId: string, threadId: string, timestamp?: number) => void;
  shouldContinueAfterError?: (threadId: string, turnId: string) => boolean;
  reconcilePlan?: (workspaceId: string, threadId: string) => Promise<void>;
  executionModelId?: string | null;
};

function newExecutionId() {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return `execution-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

const MAX_TRACKED_PLAN_TURNS = 8;
const TERMINAL_PLAN_STALE_DELAY_MS = 500;

function rememberRecentTurnId(
  store: Record<string, string[]>,
  threadId: string,
  turnId: string,
) {
  const current = store[threadId] ?? [];
  store[threadId] = [...current.filter((candidate) => candidate !== turnId), turnId]
    .slice(-MAX_TRACKED_PLAN_TURNS);
}

function hasRecentTurnId(
  store: Record<string, string[]>,
  threadId: string,
  turnId: string,
) {
  return store[threadId]?.includes(turnId) === true;
}

export function useThreadTurnEvents({
  dispatch,
  planByThreadRef,
  getCurrentRateLimits,
  getCustomName,
  isThreadHidden,
  setThreadLoaded,
  markProcessing,
  markReviewing,
  setActiveTurnId,
  getActiveTurnId,
  pendingInterruptsRef,
  pushThreadErrorMessage,
  safeMessageActivity,
  recordThreadActivity,
  shouldContinueAfterError,
  reconcilePlan,
  executionModelId,
}: UseThreadTurnEventsOptions) {
  const immediateActiveTurnIdByThreadRef = useRef<Record<string, string | null>>({});
  const lastReducerActiveTurnIdByThreadRef = useRef<Record<string, string | null>>({});
  const hasOptimisticActiveTurnByThreadRef = useRef<Record<string, boolean>>({});
  const continuationPendingByThreadRef = useRef<Record<string, boolean>>({});
  const lastExecutionTurnIdByThreadRef = useRef<Record<string, string>>({});
  const lastFinalizedTurnIdByThreadRef = useRef<Record<string, string>>({});
  const terminalActivityPendingByThreadRef = useRef<Record<string, boolean>>({});
  const terminalPlanTurnIdsByThreadRef = useRef<Record<string, string[]>>({});
  const reconciledPlanTurnIdsByThreadRef = useRef<Record<string, string[]>>({});
  const terminalPlanActivityAtByThreadRef = useRef<Record<string, number>>({});
  const activeItemCountByThreadRef = useRef<Record<string, number>>({});
  const terminalPlanStaleTimersByThreadRef = useRef<
    Record<string, ReturnType<typeof setTimeout>>
  >({});

  const setPlan = useCallback(
    (threadId: string, plan: TurnPlan | null) => {
      planByThreadRef.current = {
        ...planByThreadRef.current,
        [threadId]: plan,
      };
      dispatch({ type: "setThreadPlan", threadId, plan });
    },
    [dispatch, planByThreadRef],
  );

  const clearPlan = useCallback(
    (threadId: string) => {
      planByThreadRef.current = {
        ...planByThreadRef.current,
        [threadId]: null,
      };
      dispatch({ type: "clearThreadPlan", threadId });
    },
    [dispatch, planByThreadRef],
  );

  const clearTerminalPlanStaleTimer = useCallback((threadId: string) => {
    const timer = terminalPlanStaleTimersByThreadRef.current[threadId];
    if (timer) {
      clearTimeout(timer);
      delete terminalPlanStaleTimersByThreadRef.current[threadId];
    }
  }, []);

  const scheduleTerminalPlanStale = useCallback(
    (threadId: string, turnId: string) => {
      if (!turnId) {
        return;
      }
      clearTerminalPlanStaleTimer(threadId);
      const activityAt = terminalPlanActivityAtByThreadRef.current[threadId] ?? 0;
      terminalPlanStaleTimersByThreadRef.current[threadId] = setTimeout(() => {
        if (terminalPlanActivityAtByThreadRef.current[threadId] !== activityAt) {
          return;
        }
        const latestPlan = planByThreadRef.current[threadId];
        if (
          !hasRecentTurnId(terminalPlanTurnIdsByThreadRef.current, threadId, turnId) ||
          !latestPlan ||
          latestPlan.turnId !== turnId ||
          latestPlan.steps.length === 0 ||
          latestPlan.steps.every((step) => step.status === "completed") ||
          (activeItemCountByThreadRef.current[threadId] ?? 0) > 0
        ) {
          return;
        }
        setPlan(threadId, { ...latestPlan, syncState: "stale" });
      }, TERMINAL_PLAN_STALE_DELAY_MS);
    },
    [clearTerminalPlanStaleTimer, planByThreadRef, setPlan],
  );

  useEffect(
    () => () => {
      Object.values(terminalPlanStaleTimersByThreadRef.current).forEach((timer) => {
        clearTimeout(timer);
      });
      terminalPlanStaleTimersByThreadRef.current = {};
    },
    [],
  );

  const getLatestKnownActiveTurnId = useCallback(
    (threadId: string) => {
      const reducerTurnId = getActiveTurnId(threadId);
      const lastReducerTurnId = lastReducerActiveTurnIdByThreadRef.current[threadId];
      const immediateTurnId = immediateActiveTurnIdByThreadRef.current[threadId];
      const hasOptimisticTurn =
        hasOptimisticActiveTurnByThreadRef.current[threadId] === true;

      if (hasOptimisticTurn && immediateTurnId !== undefined) {
        if (reducerTurnId === immediateTurnId) {
          // Reducer caught up with our optimistic write.
          hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
        } else if (
          lastReducerTurnId !== undefined &&
          reducerTurnId !== lastReducerTurnId
        ) {
          // Reducer changed independently (e.g. resume hydration), so adopt it.
          hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
          immediateActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
        } else {
          lastReducerActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
          return immediateTurnId;
        }
      }

      if (lastReducerTurnId !== reducerTurnId) {
        // Keep cache aligned with reducer when we are not in an optimistic window.
        lastReducerActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
        immediateActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
      }

      if (immediateTurnId !== undefined) {
        return immediateActiveTurnIdByThreadRef.current[threadId];
      }
      return reducerTurnId;
    },
    [getActiveTurnId],
  );

  const shouldClearCompletedPlan = useCallback(
    (threadId: string, turnId: string) =>
      shouldClearCompletedPlanForThread(planByThreadRef, threadId, turnId),
    [planByThreadRef],
  );

  const clearCompletedPlan = useCallback(
    (threadId: string, turnId: string) => {
      if (shouldClearCompletedPlan(threadId, turnId)) {
        clearPlan(threadId);
        return true;
      }
      return false;
    },
    [clearPlan, shouldClearCompletedPlan],
  );

  const reconcileTerminalPlan = useCallback(
    (workspaceId: string, threadId: string, turnId: string) => {
      const resolvedTurnId = turnId || planByThreadRef.current[threadId]?.turnId || "";
      if (!resolvedTurnId) {
        return;
      }
      terminalPlanActivityAtByThreadRef.current[threadId] = Date.now();
      rememberRecentTurnId(
        terminalPlanTurnIdsByThreadRef.current,
        threadId,
        resolvedTurnId,
      );
      if (clearCompletedPlan(threadId, resolvedTurnId)) {
        return;
      }
      const plan = planByThreadRef.current[threadId];
      if (!plan || plan.turnId !== resolvedTurnId || plan.steps.length === 0) {
        return;
      }
      if (
        hasRecentTurnId(
          reconciledPlanTurnIdsByThreadRef.current,
          threadId,
          resolvedTurnId,
        )
      ) {
        return;
      }
      rememberRecentTurnId(
        reconciledPlanTurnIdsByThreadRef.current,
        threadId,
        resolvedTurnId,
      );
      setPlan(threadId, { ...plan, syncState: "reconciling" });

      void (reconcilePlan?.(workspaceId, threadId) ?? Promise.resolve())
        .catch(() => undefined)
        .then(() => {
          const latestPlan = planByThreadRef.current[threadId];
          if (
            !hasRecentTurnId(
              terminalPlanTurnIdsByThreadRef.current,
              threadId,
              resolvedTurnId,
            ) ||
            !latestPlan ||
            latestPlan.turnId !== resolvedTurnId
          ) {
            return;
          }
          if (clearCompletedPlan(threadId, resolvedTurnId)) {
            return;
          }
          scheduleTerminalPlanStale(threadId, resolvedTurnId);
        });
    },
    [clearCompletedPlan, planByThreadRef, reconcilePlan, scheduleTerminalPlanStale, setPlan],
  );

  const onThreadActivity = useCallback(
    (
      _workspaceId: string,
      threadId: string,
      activityType: "active" | "started" | "completed" = "active",
    ) => {
      if (activityType === "started") {
        activeItemCountByThreadRef.current[threadId] =
          (activeItemCountByThreadRef.current[threadId] ?? 0) + 1;
      } else if (activityType === "completed") {
        activeItemCountByThreadRef.current[threadId] = Math.max(
          0,
          (activeItemCountByThreadRef.current[threadId] ?? 0) - 1,
        );
      }
      const plan = planByThreadRef.current[threadId];
      if (
        !plan ||
        !hasRecentTurnId(
          terminalPlanTurnIdsByThreadRef.current,
          threadId,
          plan.turnId,
        )
      ) {
        return;
      }
      terminalPlanActivityAtByThreadRef.current[threadId] = Date.now();
      if (plan.syncState === "stale" || plan.syncState === "reconciling") {
        setPlan(threadId, { ...plan, syncState: "live" });
      }
      if ((activeItemCountByThreadRef.current[threadId] ?? 0) > 0) {
        clearTerminalPlanStaleTimer(threadId);
      } else {
        scheduleTerminalPlanStale(threadId, plan.turnId);
      }
    },
    [clearTerminalPlanStaleTimer, planByThreadRef, scheduleTerminalPlanStale, setPlan],
  );

  const finalizeTerminalTurn = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      status: "completed" | "interrupted" | "failed",
    ) => {
      const alreadyFinalized = Boolean(
        turnId && lastFinalizedTurnIdByThreadRef.current[threadId] === turnId,
      );
      const hasPendingActivity =
        terminalActivityPendingByThreadRef.current[threadId] === true;
      const shouldFinalizeTurn = Boolean(turnId && !alreadyFinalized);
      const shouldFinalizeActivity = shouldFinalizeTurn || hasPendingActivity;
      terminalActivityPendingByThreadRef.current[threadId] = false;
      if (!shouldFinalizeActivity) {
        return;
      }

      const timestamp = Date.now();
      if (shouldFinalizeTurn) {
        dispatch({
          type: "completeTurnExecution",
          threadId,
          turnId,
          status,
          timestamp,
        });
        lastFinalizedTurnIdByThreadRef.current[threadId] = turnId;
      }
      dispatch({
        type: "setThreadTimestamp",
        workspaceId,
        threadId,
        timestamp,
      });
      recordThreadActivity(workspaceId, threadId, timestamp);
    },
    [dispatch, recordThreadActivity],
  );

  const onThreadStarted = useCallback(
    (workspaceId: string, thread: Record<string, unknown>) => {
      const threadId = asString(thread.id);
      if (!threadId) {
        return;
      }
      const threadStartAction = getThreadStartAction(
        workspaceId,
        threadId,
        thread,
        isThreadHidden,
      );
      if (threadStartAction === "skip") {
        return;
      }
      if (threadStartAction === "hide") {
        dispatch({ type: "hideThread", workspaceId, threadId });
        return;
      }
      if (shouldIgnoreOrphanSubagentThread(thread)) {
        return;
      }
      const subagentSummaryPatch = getLiveThreadSubagentSummaryPatch(thread);
      dispatch({ type: "ensureThread", workspaceId, threadId });
      if (subagentSummaryPatch) {
        dispatch({
          type: "mergeThreadSummary",
          workspaceId,
          threadId,
          patch: subagentSummaryPatch,
        });
      }
      const timestamp = getThreadTimestamp(thread);
      const activityTimestamp = timestamp > 0 ? timestamp : Date.now();
      recordThreadActivity(workspaceId, threadId, activityTimestamp);
      dispatch({
        type: "setThreadTimestamp",
        workspaceId,
        threadId,
        timestamp: activityTimestamp,
      });

      const customName = getCustomName(workspaceId, threadId);
      if (!customName) {
        const name = getThreadDisplayTitle(thread);
        if (name) {
          dispatch({ type: "setThreadName", workspaceId, threadId, name });
        }
      }
      safeMessageActivity();
    },
    [dispatch, getCustomName, isThreadHidden, recordThreadActivity, safeMessageActivity],
  );

  const onThreadNameUpdated = useCallback(
    (
      workspaceId: string,
      payload: { threadId: string; threadName: string | null },
    ) => {
      const { threadId, threadName } = payload;
      if (!threadId || !threadName) {
        return;
      }
      const normalizedThreadId = threadId.trim().toLowerCase();
      const normalizedThreadName = threadName.trim();
      if (
        normalizedThreadName.toLowerCase() === normalizedThreadId &&
        looksAutoGeneratedThreadName(normalizedThreadName)
      ) {
        return;
      }
      if (getCustomName(workspaceId, threadId)) {
        return;
      }
      dispatch({
        type: "setThreadName",
        workspaceId,
        threadId,
        name: normalizedThreadName,
      });
    },
    [dispatch, getCustomName],
  );

  const onThreadArchived = useCallback(
    (workspaceId: string, threadId: string) => {
      if (!threadId) {
        return;
      }
      dispatch({ type: "removeThread", workspaceId, threadId });
    },
    [dispatch],
  );

  const onThreadUnarchived = useCallback(
    (workspaceId: string, threadId: string) => {
      if (!threadId) {
        return;
      }
      dispatch({ type: "ensureThread", workspaceId, threadId });
      const customName = getCustomName(workspaceId, threadId);
      if (customName) {
        dispatch({
          type: "setThreadName",
          workspaceId,
          threadId,
          name: customName,
        });
      }
      const timestamp = Date.now();
      dispatch({
        type: "setThreadTimestamp",
        workspaceId,
        threadId,
        timestamp,
      });
      recordThreadActivity(workspaceId, threadId, timestamp);
      safeMessageActivity();
    },
    [dispatch, getCustomName, recordThreadActivity, safeMessageActivity],
  );

  const onTurnStarted = useCallback(
    (workspaceId: string, threadId: string, turnId: string) => {
      const continuesExecution = continuationPendingByThreadRef.current[threadId] === true;
      const timestamp = Date.now();
      terminalActivityPendingByThreadRef.current[threadId] = true;
      dispatch({
        type: "ensureThread",
        workspaceId,
        threadId,
      });
      dispatch({ type: "setThreadTurnDiff", threadId, diff: "" });
      if (turnId) {
        clearTerminalPlanStaleTimer(threadId);
        dispatch({
          type: "startTurnExecution",
          workspaceId,
          threadId,
          turnId,
          executionId: newExecutionId(),
          modelId: executionModelId ?? null,
          timestamp,
          continueExecution: continuesExecution,
        });
        lastExecutionTurnIdByThreadRef.current[threadId] = turnId;
        continuationPendingByThreadRef.current[threadId] = false;
      }
      if (pendingInterruptsRef.current.has(threadId)) {
        pendingInterruptsRef.current.delete(threadId);
        if (turnId) {
          dispatch({
            type: "completeTurnExecution",
            threadId,
            turnId,
            status: "interrupted",
            timestamp,
          });
          void interruptTurnService(workspaceId, threadId, turnId).catch(() => {});
        }
        return;
      }
      markProcessing(threadId, true);
      if (turnId) {
        lastReducerActiveTurnIdByThreadRef.current[threadId] =
          getActiveTurnId(threadId);
        hasOptimisticActiveTurnByThreadRef.current[threadId] = true;
        immediateActiveTurnIdByThreadRef.current[threadId] = turnId;
        setActiveTurnId(threadId, turnId);
      }
    },
    [
      dispatch,
      clearTerminalPlanStaleTimer,
      getActiveTurnId,
      markProcessing,
      pendingInterruptsRef,
      setActiveTurnId,
      executionModelId,
    ],
  );

  const onTurnCompleted = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      status: "completed" | "interrupted" | "failed" = "completed",
    ) => {
      const activeTurnId = getLatestKnownActiveTurnId(threadId);
      if (turnId && activeTurnId && turnId !== activeTurnId) {
        return;
      }
      const terminalTurnId = turnId || lastExecutionTurnIdByThreadRef.current[threadId];
      finalizeTerminalTurn(workspaceId, threadId, terminalTurnId, status);
      continuationPendingByThreadRef.current[threadId] = false;
      markProcessing(threadId, false);
      resetThreadTurnState(
        {
          hasOptimisticActiveTurnByThreadRef,
          immediateActiveTurnIdByThreadRef,
          pendingInterruptsRef,
        },
        threadId,
      );
      setActiveTurnId(threadId, null);
      reconcileTerminalPlan(workspaceId, threadId, turnId);
    },
    [
      finalizeTerminalTurn,
      getLatestKnownActiveTurnId,
      markProcessing,
      pendingInterruptsRef,
      reconcileTerminalPlan,
      setActiveTurnId,
    ],
  );

  const onThreadStatusChanged = useCallback(
    (workspaceId: string, threadId: string, status: Record<string, unknown>) => {
      const statusType = normalizeThreadStatusType(status);
      if (!statusType) {
        return;
      }
      if (statusType === "active") {
        const activeTurnId = getLatestKnownActiveTurnId(threadId);
        const lastExecutionTurnId = lastExecutionTurnIdByThreadRef.current[threadId];
        const lastFinalizedTurnId = lastFinalizedTurnIdByThreadRef.current[threadId];
        const isStatusOnlyAfterTerminalTurn = Boolean(
          lastExecutionTurnId &&
            lastFinalizedTurnId === lastExecutionTurnId &&
            !activeTurnId &&
            !continuationPendingByThreadRef.current[threadId],
        );
        if (isStatusOnlyAfterTerminalTurn) {
          return;
        }
        terminalActivityPendingByThreadRef.current[threadId] = true;
        markProcessing(threadId, true);
        return;
      }
      const terminalTurnId =
        getLatestKnownActiveTurnId(threadId) ?? lastExecutionTurnIdByThreadRef.current[threadId];
      if (statusType === "interrupted") {
        finalizeTerminalTurn(
          workspaceId,
          threadId,
          terminalTurnId ?? "",
          "interrupted",
        );
        continuationPendingByThreadRef.current[threadId] = false;
        markProcessing(threadId, false);
        setActiveTurnId(threadId, null);
        reconcileTerminalPlan(workspaceId, threadId, terminalTurnId ?? "");
        return;
      }
      if (
        statusType === "idle" ||
        statusType === "notloaded" ||
        statusType === "systemerror"
      ) {
        if (!continuationPendingByThreadRef.current[threadId]) {
          finalizeTerminalTurn(
            workspaceId,
            threadId,
            terminalTurnId ?? "",
            statusType === "systemerror" ? "failed" : "completed",
          );
          reconcileTerminalPlan(workspaceId, threadId, terminalTurnId ?? "");
        }
        markProcessing(threadId, false);
        if (statusType === "notloaded") {
          setThreadLoaded(threadId, false);
          markReviewing(threadId, false);
        }
        resetThreadTurnState(
          {
            hasOptimisticActiveTurnByThreadRef,
            immediateActiveTurnIdByThreadRef,
            pendingInterruptsRef,
          },
          threadId,
        );
        setActiveTurnId(threadId, null);
      }
    },
    [
      finalizeTerminalTurn,
      getLatestKnownActiveTurnId,
      markProcessing,
      markReviewing,
      pendingInterruptsRef,
      reconcileTerminalPlan,
      setActiveTurnId,
      setThreadLoaded,
    ],
  );

  const onThreadClosed = useCallback(
    (workspaceId: string, threadId: string) => {
      const activeTurnId = getLatestKnownActiveTurnId(threadId);
      const terminalTurnId =
        activeTurnId ?? lastExecutionTurnIdByThreadRef.current[threadId] ?? "";
      finalizeTerminalTurn(workspaceId, threadId, terminalTurnId, "failed");
      continuationPendingByThreadRef.current[threadId] = false;
      setThreadLoaded(threadId, false);
      markProcessing(threadId, false);
      markReviewing(threadId, false);
      resetThreadTurnState(
        {
          hasOptimisticActiveTurnByThreadRef,
          immediateActiveTurnIdByThreadRef,
          pendingInterruptsRef,
        },
        threadId,
      );
      setActiveTurnId(threadId, null);
      if (activeTurnId) {
        pushThreadErrorMessage(
          threadId,
          "Turn failed: Codex app-server stopped unexpectedly.",
          activeTurnId,
        );
        safeMessageActivity();
      }
    },
    [
      finalizeTerminalTurn,
      getLatestKnownActiveTurnId,
      markProcessing,
      markReviewing,
      pendingInterruptsRef,
      pushThreadErrorMessage,
      safeMessageActivity,
      setActiveTurnId,
      setThreadLoaded,
    ],
  );

  const onTurnPlanUpdated = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      payload: { explanation: unknown; plan: unknown },
    ) => {
      dispatch({ type: "ensureThread", workspaceId, threadId });
      const normalized = normalizePlanUpdate(
        turnId,
        payload.explanation,
        payload.plan,
      );
      if (!normalized) {
        setPlan(threadId, null);
        return;
      }
      const nextPlan = {
        ...normalized,
        syncState: "live" as const,
        updatedAt: Date.now(),
      };
      if (
        hasRecentTurnId(terminalPlanTurnIdsByThreadRef.current, threadId, turnId)
      ) {
        const currentPlan = planByThreadRef.current[threadId];
        if (currentPlan && currentPlan.turnId !== turnId) {
          return;
        }
        if (
          nextPlan.steps.length > 0 &&
          nextPlan.steps.every((step) => step.status === "completed")
        ) {
          clearTerminalPlanStaleTimer(threadId);
          clearPlan(threadId);
          return;
        }
        terminalPlanActivityAtByThreadRef.current[threadId] = Date.now();
        setPlan(threadId, { ...nextPlan, syncState: "live" });
        scheduleTerminalPlanStale(threadId, turnId);
        return;
      }
      clearTerminalPlanStaleTimer(threadId);
      setPlan(threadId, nextPlan);
    },
    [clearPlan, clearTerminalPlanStaleTimer, dispatch, planByThreadRef, scheduleTerminalPlanStale, setPlan],
  );

  const onTurnDiffUpdated = useCallback(
    (workspaceId: string, threadId: string, diff: string) => {
      const turnId = getLatestKnownActiveTurnId(threadId);
      dispatch({ type: "ensureThread", workspaceId, threadId });
      dispatch({ type: "setThreadTurnDiff", threadId, diff });
      if (turnId) {
        dispatch({
          type: "updateTurnExecutionDiff",
          threadId,
          turnId,
          diff,
          timestamp: Date.now(),
        });
      }
    },
    [dispatch, getLatestKnownActiveTurnId],
  );

  const onThreadTokenUsageUpdated = useCallback(
    (
      workspaceId: string,
      threadId: string,
      tokenUsage: Record<string, unknown> | null,
    ) => {
      dispatch({ type: "ensureThread", workspaceId, threadId });
      dispatch({
        type: "setThreadTokenUsage",
        threadId,
        tokenUsage: normalizeTokenUsage(tokenUsage),
      });
    },
    [dispatch],
  );

  const onAccountRateLimitsUpdated = useCallback(
    (workspaceId: string, rateLimits: Record<string, unknown>) => {
      const previousRateLimits = getCurrentRateLimits?.(workspaceId) ?? null;
      dispatch({
        type: "setRateLimits",
        workspaceId,
        rateLimits: normalizeRateLimits(rateLimits, previousRateLimits),
      });
    },
    [dispatch, getCurrentRateLimits],
  );

  const onTurnError = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      payload: { message: string; willRetry: boolean },
    ) => {
      if (payload.willRetry) {
        continuationPendingByThreadRef.current[threadId] = true;
        return;
      }
      if (shouldContinueAfterError?.(threadId, turnId)) {
        continuationPendingByThreadRef.current[threadId] = true;
        return;
      }
      const activeTurnId = getLatestKnownActiveTurnId(threadId);
      if (turnId && activeTurnId && turnId !== activeTurnId) {
        return;
      }
      const terminalTurnId = turnId || lastExecutionTurnIdByThreadRef.current[threadId];
      finalizeTerminalTurn(workspaceId, threadId, terminalTurnId, "failed");
      continuationPendingByThreadRef.current[threadId] = false;
      dispatch({ type: "ensureThread", workspaceId, threadId });
      markProcessing(threadId, false);
      markReviewing(threadId, false);
      resetThreadTurnState(
        {
          hasOptimisticActiveTurnByThreadRef,
          immediateActiveTurnIdByThreadRef,
          pendingInterruptsRef,
        },
        threadId,
      );
      setActiveTurnId(threadId, null);
      const message = payload.message
        ? `Turn failed: ${payload.message}`
        : "Turn failed.";
      pushThreadErrorMessage(threadId, message, terminalTurnId || undefined);
      safeMessageActivity();
    },
    [
      dispatch,
      finalizeTerminalTurn,
      getLatestKnownActiveTurnId,
      markProcessing,
      markReviewing,
      pendingInterruptsRef,
      pushThreadErrorMessage,
      safeMessageActivity,
      setActiveTurnId,
      shouldContinueAfterError,
    ],
  );

  return {
    onThreadStarted,
    onThreadNameUpdated,
    onThreadArchived,
    onThreadUnarchived,
    onTurnStarted,
    onTurnCompleted,
    onThreadStatusChanged,
    onThreadClosed,
    onThreadActivity,
    onTurnPlanUpdated,
    onTurnDiffUpdated,
    onThreadTokenUsageUpdated,
    onAccountRateLimitsUpdated,
    onTurnError,
  };
}
