import type { ConversationItem } from "@/types";
import {
  normalizeItem,
  prepareThreadItems,
  sameMessageAttachments,
  sameMessageImages,
  upsertItem,
} from "@utils/threadItems";
import type { ThreadAction, ThreadState } from "../useThreadsReducer";
import {
  addSummaryBoundary,
  dropLatestLocalReviewStart,
  ensureUniqueReviewId,
  extractRenameText,
  findMatchingReview,
  isDuplicateReviewById,
  looksAutoGeneratedThreadName,
  maybeRenameThreadFromAgent,
  mergeStreamingText,
  prefersUpdatedSort,
} from "./common";

function clearInterruptedThread(
  state: ThreadState,
  threadId: string,
): Pick<ThreadState, "interruptedThreadById"> {
  if (!state.interruptedThreadById[threadId]) {
    return { interruptedThreadById: state.interruptedThreadById };
  }
  const { [threadId]: _, ...rest } = state.interruptedThreadById;
  return { interruptedThreadById: rest };
}

function prepareLiveThreadItems(
  items: ConversationItem[],
  maxItemsPerThread: number | null,
) {
  return prepareThreadItems(items, { maxItemsPerThread });
}

function mergeCompletedContextCompactionIds(
  current: Record<string, true> | undefined,
  items: ConversationItem[],
) {
  let next = current;
  items.forEach((item) => {
    if (
      item.kind !== "tool" ||
      item.toolType !== "contextCompaction" ||
      item.status !== "completed" ||
      next?.[item.id]
    ) {
      return;
    }
    next = { ...(next ?? {}), [item.id]: true };
  });
  return next;
}

export function reduceThreadItems(state: ThreadState, action: ThreadAction): ThreadState {
  switch (action.type) {
    case "addAssistantMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const message: ConversationItem = {
        id: `${Date.now()}-assistant`,
        kind: "message",
        role: "assistant",
        text: action.text,
        createdAt: Date.now(),
        ...(action.turnId ? { turnId: action.turnId } : {}),
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareLiveThreadItems(
            [...list, message],
            state.maxItemsPerThread,
          ),
        },
      };
    }
    case "appendAgentDelta": {
      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      const index = list.findIndex((msg) => msg.id === action.itemId);
      if (index >= 0 && list[index].kind === "message") {
        const existing = list[index];
        list[index] = {
          ...existing,
          text: mergeStreamingText(existing.text, action.delta),
          ...(action.turnId && !existing.turnId
            ? { turnId: action.turnId }
            : {}),
          createdAt: existing.createdAt ?? Date.now(),
        };
      } else {
        list.push({
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.delta,
          ...(action.turnId ? { turnId: action.turnId } : {}),
          createdAt: Date.now(),
        });
      }
      const updatedItems = prepareLiveThreadItems(list, state.maxItemsPerThread);
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        ...clearInterruptedThread(state, action.threadId),
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "completeAgentMessage": {
      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      const index = list.findIndex((msg) => msg.id === action.itemId);
      if (index >= 0 && list[index].kind === "message") {
        const existing = list[index];
        list[index] = {
          ...existing,
          text: action.text || existing.text,
          ...(action.phase ? { phase: action.phase } : {}),
          ...(action.turnId ? { turnId: action.turnId } : {}),
          createdAt: existing.createdAt ?? Date.now(),
        };
      } else {
        list.push({
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.text,
          ...(action.phase ? { phase: action.phase } : {}),
          ...(action.turnId ? { turnId: action.turnId } : {}),
          createdAt: Date.now(),
        });
      }
      const updatedItems = prepareLiveThreadItems(list, state.maxItemsPerThread);
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        ...clearInterruptedThread(state, action.threadId),
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "upsertItem": {
      let list = state.itemsByThread[action.threadId] ?? [];
      const item = normalizeItem(action.item);
      const isUserMessage = item.kind === "message" && item.role === "user";
      const hadUserMessage = isUserMessage
        ? list.some((entry) => entry.kind === "message" && entry.role === "user")
        : false;
      const renameText = isUserMessage ? extractRenameText(item.text) : "";
      if (
        item.kind === "review" &&
        item.state === "started" &&
        !item.id.startsWith("review-start-")
      ) {
        list = dropLatestLocalReviewStart(list);
      }
      if (item.kind === "review" && isDuplicateReviewById(list, item)) {
        return state;
      }
      if (item.kind === "review") {
        const existing = findMatchingReview(list, item);
        if (existing && existing.id !== item.id) {
          return state;
        }
      }
      const nextItem = ensureUniqueReviewId(list, item);
      const userMessage =
        nextItem.kind === "message" && nextItem.role === "user"
          ? nextItem
          : null;
      const existingIndex = list.findIndex((entry) => entry.id === nextItem.id);
      const pendingReplacement =
        userMessage ? state.pendingUserMessageReplacementByThread[action.threadId] : null;
      const pendingReplacementIndex = pendingReplacement
        ? list.findIndex((entry) => entry.id === pendingReplacement.messageId)
        : -1;
      const shouldReplacePendingEcho =
        userMessage &&
        pendingReplacement &&
        pendingReplacementIndex >= 0 &&
        nextItem.id !== pendingReplacement.messageId &&
        userMessage.text === pendingReplacement.text &&
        sameMessageImages(userMessage.images, pendingReplacement.images) &&
        sameMessageAttachments(userMessage.attachments, pendingReplacement.attachments);
      const nextList =
        action.replaceExisting && existingIndex >= 0
          ? [
              ...list.slice(0, existingIndex),
              nextItem,
              ...list.slice(existingIndex + 1),
            ]
          : shouldReplacePendingEcho
            ? [
                ...list.slice(0, pendingReplacementIndex),
                nextItem,
                ...list.slice(pendingReplacementIndex + 1),
              ]
          : upsertItem(list, nextItem);
      const updatedItems = prepareLiveThreadItems(nextList, state.maxItemsPerThread);
      const completedContextCompactionIds = mergeCompletedContextCompactionIds(
        state.completedContextCompactionIdsByThread[action.threadId],
        [nextItem],
      );
      const nextPendingUserMessageReplacementByThread =
        action.replaceExisting && userMessage
          ? {
              ...state.pendingUserMessageReplacementByThread,
              [action.threadId]: {
                messageId: userMessage.id,
                text: userMessage.text,
                images: userMessage.images,
                attachments: userMessage.attachments,
              },
            }
          : shouldReplacePendingEcho
            ? (() => {
                const {
                  [action.threadId]: _,
                  ...rest
                } = state.pendingUserMessageReplacementByThread;
                return rest;
              })()
            : state.pendingUserMessageReplacementByThread;
      let nextThreadsByWorkspace = state.threadsByWorkspace;
      if (isUserMessage) {
        const threads = state.threadsByWorkspace[action.workspaceId] ?? [];
        const textValue = renameText;
        const updatedThreads = threads.map((thread) => {
          if (thread.id !== action.threadId) {
            return thread;
          }
          const looksAutoGenerated = looksAutoGeneratedThreadName(thread.name);
          const shouldRename =
            !hadUserMessage &&
            textValue.length > 0 &&
            looksAutoGenerated &&
            !action.hasCustomName;
          const nextName =
            shouldRename && textValue.length > 38
              ? `${textValue.slice(0, 38)}…`
              : shouldRename
                ? textValue
                : thread.name;
          return { ...thread, name: nextName };
        });
        const bumpedThreads =
          prefersUpdatedSort(state, action.workspaceId) && updatedThreads.length
            ? [
                ...updatedThreads.filter((thread) => thread.id === action.threadId),
                ...updatedThreads.filter((thread) => thread.id !== action.threadId),
              ]
            : updatedThreads;
        nextThreadsByWorkspace = {
          ...state.threadsByWorkspace,
          [action.workspaceId]: bumpedThreads,
        };
      }
      return {
        ...state,
        ...(isUserMessage ? clearInterruptedThread(state, action.threadId) : {}),
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
        pendingUserMessageReplacementByThread:
          nextPendingUserMessageReplacementByThread,
        completedContextCompactionIdsByThread:
          completedContextCompactionIds ===
          state.completedContextCompactionIdsByThread[action.threadId]
            ? state.completedContextCompactionIdsByThread
            : {
                ...state.completedContextCompactionIdsByThread,
                [action.threadId]: completedContextCompactionIds ?? {},
              },
      };
    }
    case "setItemTurnId": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((item) => item.id === action.itemId);
      if (index < 0 || list[index].turnId === action.turnId) {
        return state;
      }
      const nextList = [...list];
      nextList[index] = { ...nextList[index], turnId: action.turnId };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareLiveThreadItems(
            nextList,
            state.maxItemsPerThread,
          ),
        },
      };
    }
    case "removeItem": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const nextList = list.filter((item) => item.id !== action.itemId);
      if (nextList.length === list.length) {
        return state;
      }
      const pendingReplacement =
        state.pendingUserMessageReplacementByThread[action.threadId];
      const nextPendingUserMessageReplacementByThread =
        pendingReplacement?.messageId === action.itemId
          ? (() => {
              const {
                [action.threadId]: _,
                ...rest
              } = state.pendingUserMessageReplacementByThread;
              return rest;
            })()
          : state.pendingUserMessageReplacementByThread;
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareLiveThreadItems(
            nextList,
            state.maxItemsPerThread,
          ),
        },
        pendingUserMessageReplacementByThread:
          nextPendingUserMessageReplacementByThread,
      };
    }
    case "setThreadItems": {
      const completedContextCompactionIds = mergeCompletedContextCompactionIds(
        state.completedContextCompactionIdsByThread[action.threadId],
        action.items,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(action.items, {
            maxItemsPerThread:
              action.trimItems === false ? null : state.maxItemsPerThread,
          }),
        },
        completedContextCompactionIdsByThread:
          completedContextCompactionIds ===
          state.completedContextCompactionIdsByThread[action.threadId]
            ? state.completedContextCompactionIdsByThread
            : {
                ...state.completedContextCompactionIdsByThread,
                [action.threadId]: completedContextCompactionIds ?? {},
              },
      };
    }
    case "prependThreadItems": {
      const currentItems = state.itemsByThread[action.threadId] ?? [];
      const currentIds = new Set(currentItems.map((item) => item.id));
      const olderItems = action.items.filter((item) => !currentIds.has(item.id));
      if (olderItems.length === 0) {
        return state;
      }
      const mergedItems = [...olderItems, ...currentItems];
      const completedContextCompactionIds = mergeCompletedContextCompactionIds(
        state.completedContextCompactionIdsByThread[action.threadId],
        mergedItems,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(mergedItems, {
            maxItemsPerThread: null,
          }),
        },
        completedContextCompactionIdsByThread:
          completedContextCompactionIds ===
          state.completedContextCompactionIdsByThread[action.threadId]
            ? state.completedContextCompactionIdsByThread
            : {
                ...state.completedContextCompactionIdsByThread,
                [action.threadId]: completedContextCompactionIds ?? {},
              },
      };
    }
    case "evictThreadItems": {
      const residentThreadIds = action.threadIds.filter(
        (threadId) => threadId in state.itemsByThread,
      );
      if (residentThreadIds.length === 0) {
        return state;
      }
      const itemsByThread = { ...state.itemsByThread };
      residentThreadIds.forEach((threadId) => {
        delete itemsByThread[threadId];
      });
      return { ...state, itemsByThread };
    }
    case "appendReasoningSummary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        summary: mergeStreamingText(
          "summary" in base ? base.summary : "",
          action.delta,
        ),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareLiveThreadItems(next, state.maxItemsPerThread),
        },
      };
    }
    case "appendReasoningSummaryBoundary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        summary: addSummaryBoundary("summary" in base ? base.summary : ""),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareLiveThreadItems(next, state.maxItemsPerThread),
        },
      };
    }
    case "appendReasoningContent": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        content: mergeStreamingText(
          "content" in base ? base.content : "",
          action.delta,
        ),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareLiveThreadItems(next, state.maxItemsPerThread),
        },
      };
    }
    case "appendPlanDelta": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "tool"
          ? list[index]
          : {
              id: action.itemId,
              kind: "tool",
              toolType: "plan",
              title: "Plan",
              detail: "",
              status: "in_progress",
              output: "",
            };
      const existingOutput = base.kind === "tool" ? (base.output ?? "") : "";
      const updated: ConversationItem = {
        ...(base as ConversationItem),
        kind: "tool",
        toolType: "plan",
        title: "Plan",
        detail: "Generating plan...",
        status: "in_progress",
        output: mergeStreamingText(existingOutput, action.delta),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareLiveThreadItems(next, state.maxItemsPerThread),
        },
      };
    }
    case "appendToolOutput": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      if (index < 0 || list[index].kind !== "tool") {
        return state;
      }
      const existing = list[index];
      const updated: ConversationItem = {
        ...existing,
        output: mergeStreamingText(existing.output ?? "", action.delta),
      } as ConversationItem;
      const next = [...list];
      next[index] = updated;
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareLiveThreadItems(next, state.maxItemsPerThread),
        },
      };
    }
    default:
      return state;
  }
}
