import type { ThreadSummary } from "@/types";
import {
  getThreadCreatedTimestamp,
  getThreadTimestamp,
} from "@utils/threadItems";
import { extractThreadCodexMetadata } from "@threads/utils/threadCodexMetadata";
import { asString } from "@threads/utils/threadNormalize";
import {
  getParentThreadIdFromThread,
  getSubagentMetadataFromThread,
  getSubagentTaskTitleFromThread,
  isSubagentThreadSource,
  shouldHideSubagentThreadFromSidebar,
} from "@threads/utils/threadRpc";
import {
  clampThreadName,
  looksAutoGeneratedThreadName,
} from "@threads/utils/threadNaming";
import { LOCAL_CODEX_WORKSPACE_ID } from "@/features/workspaces/domain/localCodexWorkspace";

type BuildThreadSummaryFromThreadOptions = {
  workspaceId: string;
  thread: Record<string, unknown>;
  fallbackIndex: number;
  getCustomName?: (workspaceId: string, threadId: string) => string | undefined;
};

export function getThreadDisplayTitle(thread: Record<string, unknown>) {
  const formalTitle =
    asString(thread.threadName ?? "").trim() ||
    asString(thread.thread_name ?? "").trim() ||
    asString(thread.name ?? "").trim() ||
    asString(thread.title ?? "").trim();
  const subagentTaskTitle = getSubagentTaskTitleFromThread(thread);
  const rawTitle =
    (formalTitle &&
    (!subagentTaskTitle || !looksAutoGeneratedThreadName(formalTitle))
      ? formalTitle
      : "") ||
    subagentTaskTitle ||
    asString(thread.preview ?? "").trim();
  return rawTitle ? clampThreadName(rawTitle) : null;
}

export function extractThreadFromResponse(
  response: Record<string, unknown> | null | undefined,
): Record<string, unknown> | null {
  if (!response || typeof response !== "object" || Array.isArray(response)) {
    return null;
  }
  const result =
    response.result && typeof response.result === "object" && !Array.isArray(response.result)
      ? (response.result as Record<string, unknown>)
      : null;
  const thread =
    (result?.thread as Record<string, unknown> | undefined) ??
    (response.thread as Record<string, unknown> | undefined);
  return thread ?? null;
}

export function buildThreadSummaryFromThread({
  workspaceId,
  thread,
  fallbackIndex,
  getCustomName,
}: BuildThreadSummaryFromThreadOptions): ThreadSummary | null {
  const id = String(thread?.id ?? "");
  if (!id) {
    return null;
  }
  const customName = getCustomName?.(workspaceId, id);
  const fallbackName = `Agent ${fallbackIndex + 1}`;
  const displayTitle = getThreadDisplayTitle(thread);
  const nameIsFallback = !customName && !displayTitle;
  const name = customName
    ? customName
    : displayTitle ?? fallbackName;
  const metadata = extractThreadCodexMetadata(thread);
  const cwd = asString(thread.cwd ?? "").trim();
  if (shouldHideSubagentThreadFromSidebar(thread.source)) {
    return null;
  }
  const subagentMetadata = getSubagentMetadataFromThread(thread);
  const isSubagent =
    isSubagentThreadSource(thread.source) ||
    Boolean(getParentThreadIdFromThread(thread)) ||
    Boolean(subagentMetadata.nickname || subagentMetadata.role);
  return {
    id,
    name,
    ...(nameIsFallback ? { nameIsFallback: true } : {}),
    updatedAt: getThreadTimestamp(thread),
    createdAt: getThreadCreatedTimestamp(thread),
    ...(workspaceId === LOCAL_CODEX_WORKSPACE_ID && cwd ? { cwd } : {}),
    ...(metadata.modelId ? { modelId: metadata.modelId } : {}),
    ...(metadata.effort ? { effort: metadata.effort } : {}),
    ...(isSubagent ? { isSubagent: true } : {}),
    ...(isSubagent && subagentMetadata.nickname
      ? { subagentNickname: subagentMetadata.nickname }
      : {}),
    ...(isSubagent && subagentMetadata.role
      ? { subagentRole: subagentMetadata.role }
      : {}),
  };
}
